defaults: &defaults
  MQTT_HOST: fogapi.mxchip.com.cn
  MQTT_PORT: 1883

  MESSAGE_RATE: 167
  MESSAGE_DURATION: 60

  DEVICE_STEP_NUM: 200
  DEVICE_TRIAD_FILEPATH: ./configs/triads.csv

development:
  <<: *defaults
