defaults: &defaults
  MQTT_HOST: fogapi.mxchip.com.cn
  MQTT_PORT: 1883

  MESSAGE_RATE: 1000
  MESSAGE_DURATION: 120

  DEVICE_STEP_NUM: 500
  DEVICE_TRIAD_FILEPATH: ./configs/triad.csv

development:
  <<: *defaults
