defaults: &defaults
  MQTT_HOST: app.mqtt.fogcloud.io
  MQTT_PORT: 1883
  # 设备上报消息速率，单位：条/秒
  MESSAGE_RATE: 1
  # 消息上报持续时间，单位：秒
  MESSAGE_DURATION: 30000

  DEVICE_STEP_NUM: 10
  DEVICE_NUM: 10
#  DEVICE_TRIAD_FILEPATH: /etc/thingmocker/local_triad.txt
  DEVICE_TRIAD_FILEPATH: ./configs/local_triad.txt

development:
  <<: *defaults
  MQTT_HOST: app.mqtt.fogcloud.io
  MQTT_PORT: 1883
#  DEVICE_TRIAD_FILEPATH: /etc/thingmocker/local_triad.txt
  DEVICE_TRIAD_FILEPATH: ./configs/local_triad.txt