defaults: &defaults
  MQTT_HOST: api.fogcloud.io
  MQTT_PORT: 1883
  IF_ADDR: 192.168.60.180:0

  MESSAGE_RATE: 1
  MESSAGE_DURATION: 1000

  DEVICE_STEP_NUM: 10
  DEVICE_NUM: 1
  DEVICE_TRIAD_FILEPATH: ./configs/triad1.csv

development:
  <<: *defaults
  MQTT_HOST: demo.beta.fogcloud.io
  IF_ADDR: 192.168.2.112
  DEVICE_TRIAD_FILEPATH: ./configs/triad1.csv