defaults: &defaults
  MQTT_HOST: localhost
  MQTT_PORT: 1883
  IF_ADDR: 
  # 设备上报消息速率，单位：条/秒
  MESSAGE_RATE: 1000 
  # 消息上报持续时间，单位：秒
  MESSAGE_DURATION: 100_000

  DEVICE_STEP_NUM: 100
  DEVICE_NUM: 1000
  DEVICE_TRIAD_FILEPATH: ./configs/triads.txt

development:
  <<: *defaults
  MQTT_HOST: demo.beta.fogcloud.io
  IF_ADDR: 192.168.2.112
  DEVICE_TRIAD_FILEPATH: ./configs/triad1.csv