defaults: &defaults
  MQTT_HOST: localhost
  MQTT_PORT: 1883

  MESSAGE_RATE: 1000
  MESSAGE_DURATION: 100

  DEVICE_STEP_NUM: 500
  DEVICE_TRIAD_FILEPATH: ./configs/triad.csv

development:
  <<: *defaults
  MQTT_HOST: host.docker.internal

  DEVICE_TRIAD_FILEPATH: /etc/thingmocker/triad.csv